openapi: 3.0.2
info:
  title: Finix Authorizations Verifications API
  description:
    $ref: api-descriptions/main.md
  contact:
    name: Finix
    url: https://finix.com
    email: support@finixpayments.com
  version: '2022-02-01'
servers:
- description: Sandbox server to be used for testing and development
  url: https://finix.sandbox-payments-api.com
security:
- BasicAuth: []
tags:
- name: Verifications
  description:
    $ref: api-descriptions/tags/verifications.md
paths:
  /merchants/{merchant_id}/verifications:
    parameters:
    - description: ID of `Merchant` object.
      required: true
      in: path
      name: merchant_id
      schema:
        type: string
    get:
      description: Get a list of all the `Verifications` for a `Merchant` resource.
      summary: List Merchant Verifications
      operationId: listMerchantVerifications
      parameters:
      - required: false
        in: query
        name: limit
        schema:
          type: integer
          format: int64
        description: The number of entries to return.
      - $ref: '#/components/parameters/QueryAfterCursor'
      - $ref: '#/components/parameters/QueryBeforeCursor'
      responses:
        '200':
          $ref: '#/components/responses/VerificationsList'
        '401':
          $ref: '#/components/responses/ErrorUnauthorized'
        '403':
          $ref: '#/components/responses/ErrorForbidden403'
        '404':
          $ref: '#/components/responses/ErrorNotFound'
        '406':
          $ref: '#/components/responses/Error406NotAcceptable'
      x-internal: false
      x-java-method-name: listByMerchantId
      x-group-parameters: true
      tags:
      - Verifications
      x-codeSamples:
      - lang: cURL
        label: curl
        source: "curl \"https://finix.sandbox-payments-api.com/merchants/MUpaGK5dUb2Sb7aGuXhFRNbj/verifications\" \\\n  -H \"Finix-Version: 2022-02-01\" \\\n  -u USsRhsHYZGBPnQw8CByJyEQW:8a14c2f9-d94b-4c72-8f5c-a62908e5b30e\n"
      x-python-method-name: list_by_merchant_id
      x-returns-list: true
  /payment_instruments/{payment_instrument_id_verify}:
    parameters:
    - schema:
        type: string
      name: payment_instrument_id_verify
      in: path
      required: true
    get:
      tags:
      - Verifications
      description: List all the `Verifications` created for a `Payment Instrument`.
      summary: List Payment Instrument Verifications
      operationId: listPaymentInstrumentVerifications
      parameters:
      - required: false
        in: query
        name: limit
        schema:
          type: integer
          format: int64
        description: The number of entries to return.
      - required: false
        in: query
        name: offset
        schema:
          type: integer
          format: int64
        description: The number of items to skip before starting to collect the result set.
      - required: false
        in: query
        name: pageNumber
        schema:
          type: integer
          format: int64
        description: The page number to list.
      - required: false
        in: query
        name: pageSize
        schema:
          type: integer
          format: int64
        description: The size of the page.
      responses:
        '200':
          $ref: '#/components/responses/VerificationsList'
        '401':
          $ref: '#/components/responses/ErrorUnauthorized'
        '403':
          $ref: '#/components/responses/ErrorForbidden403'
        '404':
          $ref: '#/components/responses/ErrorNotFound'
        '406':
          $ref: '#/components/responses/Error406NotAcceptable'
      x-internal: false
      x-java-method-name: listByPaymentInstrumentId
      x-group-parameters: true
      x-codeSamples:
      - lang: cURL
        label: curl
        source: "curl \"https://finix.sandbox-payments-api.com/payment_instruments/PImc5nvdnp15atLxEBAGtxJs/verifications/\" \\\n  -H \"Finix-Version: 2022-02-01\" \\\n  -u USpEbizhxFRAFT7oYgWjX87B:6d3ace2c-23f9-4e59-8b75-a1a5b8a53055\n"
      x-python-method-name: list_by_payment_instrument_id
      x-returns-list: true
  /verifications:
    post:
      description: 'Create a `Verification` to verify a seller''s `Identity`.


        Verifications can also be created directly on the resources you want to verify. For example:

        - `POST /merchants/{merchant_id}/verifications`

        - `POST /payment_instruments/{payment_instrument_id}/verifications`'
      summary: Create a Merchant Verification
      operationId: createVerification
      requestBody:
        $ref: '#/components/requestBodies/CreateVerificationRequest'
      responses:
        '201':
          $ref: '#/components/responses/Verification'
        '400':
          $ref: '#/components/responses/ErrorUnprocessableEntity'
        '401':
          $ref: '#/components/responses/ErrorUnauthorized'
        '403':
          $ref: '#/components/responses/ErrorForbidden403'
        '406':
          $ref: '#/components/responses/Error406NotAcceptable'
        '422':
          $ref: '#/components/responses/Error422InvalidField'
      x-java-method-name: create
      x-codeSamples:
      - lang: cURL
        label: curl
        source:
          $ref: xcode/curl/verifications/merchant-verification.md
      tags:
      - Verifications
      x-python-method-name: create
    get:
      tags:
      - Verifications
      description: Retrieve a list of `Verifications`.
      summary: List Verifications
      operationId: listVerifications
      parameters:
      - $ref: '#/components/parameters/QueryLimit'
      - $ref: '#/components/parameters/QueryAfterCursor'
      - $ref: '#/components/parameters/QueryBeforeCursor'
      responses:
        '200':
          $ref: '#/components/responses/VerificationsList'
        '401':
          $ref: '#/components/responses/ErrorUnauthorized'
        '403':
          $ref: '#/components/responses/ErrorForbidden403'
        '406':
          $ref: '#/components/responses/Error406NotAcceptable'
      x-java-method-name: list
      x-group-parameters: true
      x-codeSamples:
      - lang: cURL
        label: curl
        source: "curl \"https://finix.sandbox-payments-api.com/verifications\" \\\n  -H \"Finix-Version: 2022-02-01\" \\\n  -u USsRhsHYZGBPnQw8CByJyEQW:8a14c2f9-d94b-4c72-8f5c-a62908e5b30e\n"
      x-python-method-name: list
      x-returns-list: true
  /verifications/{verification_id}:
    parameters:
    - description: ID of `Verification` object.
      required: true
      in: path
      name: verification_id
      schema:
        type: string
    get:
      tags:
      - Verifications
      description: Retrieve the details of a `Verification`.
      summary: Fetch a Verification
      operationId: getVerification
      responses:
        '200':
          $ref: '#/components/responses/Verification'
        '401':
          $ref: '#/components/responses/ErrorUnauthorized'
        '403':
          $ref: '#/components/responses/ErrorForbidden403'
        '404':
          $ref: '#/components/responses/ErrorNotFound'
        '406':
          $ref: '#/components/responses/Error406NotAcceptable'
      x-java-method-name: get
      x-codeSamples:
      - lang: cURL
        label: curl
        source: "curl \"https://finix.sandbox-payments-api.com/verifications/VIbXwBuccEcqw7rfZneELCv4\" \\\n  -H \"Finix-Version: 2022-02-01\" \\\n  -u USsRhsHYZGBPnQw8CByJyEQW:8a14c2f9-d94b-4c72-8f5c-a62908e5b30e\n"
      x-python-method-name: get
components:
  responses:
    Error422InvalidField:
      description: Invalid field
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error422InvalidFieldList'
    Error406NotAcceptable:
      description: Not Acceptable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error406NotAcceptable'
          examples: {}
    ErrorUnprocessableEntity:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorGeneric'
    ErrorNotFound:
      description: Object does not exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error404NotFoundList'
    VerificationsList:
      description: List of Verification objects
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VerificationsList'
          examples:
            Merchant Verification:
              value:
                _embedded:
                  verifications:
                  - id: VInHzhoRAnAizVU7jcj2K6bX
                    created_at: '2022-08-15T23:12:56.40Z'
                    updated_at: '2022-08-15T23:12:56.85Z'
                    application: APgPDQrLD52TYvqazjHJJchM
                    identity: null
                    merchant: MUpaGK5dUb2Sb7aGuXhFRNbj
                    merchant_identity: IDgahPGJ6hangmVJwrMRyZzr
                    messages: []
                    payment_instrument: null
                    processor: DUMMY_V1
                    raw: RawDummyMerchantUnderwriteResult
                    state: SUCCEEDED
                    tags: {}
                    trace_id: 1c8fb49d-6f1c-40a0-8646-1bcb88047583
                    _links:
                      self:
                        href: https://finix.sandbox-payments-api.com/verifications/VInHzhoRAnAizVU7jcj2K6bX
                      application:
                        href: https://finix.sandbox-payments-api.com/applications/APgPDQrLD52TYvqazjHJJchM
                      merchant:
                        href: https://finix.sandbox-payments-api.com/merchants/MUpaGK5dUb2Sb7aGuXhFRNbj
                  - id: VIdS8qSW3kZbnK9AsFHJZ81U
                    created_at: '2022-08-15T23:12:54.32Z'
                    updated_at: '2022-08-15T23:12:54.65Z'
                    application: APgPDQrLD52TYvqazjHJJchM
                    identity: null
                    merchant: MUpaGK5dUb2Sb7aGuXhFRNbj
                    merchant_identity: IDgahPGJ6hangmVJwrMRyZzr
                    messages: []
                    payment_instrument: null
                    processor: DUMMY_V1
                    raw: RawDummyMerchantUnderwriteResult
                    state: SUCCEEDED
                    tags:
                      key: value_2
                    trace_id: 4d12cbe6-032d-4e9d-8291-ce16f4add412
                    _links:
                      self:
                        href: https://finix.sandbox-payments-api.com/verifications/VIdS8qSW3kZbnK9AsFHJZ81U
                      application:
                        href: https://finix.sandbox-payments-api.com/applications/APgPDQrLD52TYvqazjHJJchM
                      merchant:
                        href: https://finix.sandbox-payments-api.com/merchants/MUpaGK5dUb2Sb7aGuXhFRNbj
                _links:
                  self:
                    href: https://finix.sandbox-payments-api.com/merchants/MUpaGK5dUb2Sb7aGuXhFRNbj/verifications?offset=0&limit=20&sort=created_at,desc&sort=id,desc
                page:
                  offset: 0
                  limit: 20
                  count: 2
            Payment Instrument Verification:
              value:
                _embedded:
                  verifications:
                  - id: VIixxYGRVewLFa3GqSzqKPbw
                    created_at: '2022-02-04T18:33:14.50Z'
                    updated_at: '2022-02-04T18:33:15.69Z'
                    application: AP83dL8NE1Q7KfQo9onGg76M
                    identity: null
                    merchant: null
                    merchant_identity: null
                    messages: []
                    payment_instrument: PImc5nvdnp15atLxEBAGtxJs
                    processor: VISA_V1
                    raw:
                      validation_details:
                        systems_trace_audit_number: '203518208518'
                        error_result: null
                        transaction_identifier: '287371129315250'
                        approval_code: null
                        action_code: '25'
                        response_code: '5'
                        address_verification_results: I
                        cvv2_result_code: P
                      inquiry_details:
                        systems_trace_audit_number: '203518208518'
                        error_result: null
                        visa_network_info:
                        - card_type_code: D
                          billing_currency_code: 840
                          billing_currency_minor_digits: 2
                          issuer_name: Visa Test Bank
                          card_issuer_country_code: 840
                          fast_funds_indicator: D
                          push_funds_block_indicator: C
                          online_gambing_block_indicator: N
                        ppgs_network_info: []
                    state: SUCCEEDED
                    tags: {}
                    trace_id: '203518208518'
                    _links:
                      self:
                        href: https://finix.sandbox-payments-api.com/verifications/VIixxYGRVewLFa3GqSzqKPbw
                      application:
                        href: https://finix.sandbox-payments-api.com/applications/AP83dL8NE1Q7KfQo9onGg76M
                      payment_instrument:
                        href: https://finix.sandbox-payments-api.com/payment_instruments/PImc5nvdnp15atLxEBAGtxJs
                _links:
                  self:
                    href: https://finix.sandbox-payments-api.com/payment_instruments/PImc5nvdnp15atLxEBAGtxJs/verifications/?offset=0&limit=20&sort=created_at,desc&sort=id,desc
                page:
                  offset: 0
                  limit: 20
                  count: 1
      headers:
        finix-apiuser-role:
          $ref: '#/components/headers/finix-apiuser-role'
        date:
          $ref: '#/components/headers/date'
        x-request-id:
          $ref: '#/components/headers/x-request-id'
    Verification:
      description: Single Verification object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Verification'
          examples:
            Payment Instrument - Verify a Card’s CVV:
              value:
                id: VIvZKP8XKzxyJaxJsfAEHbw6
                created_at: '2022-10-11T00:46:48.68Z'
                updated_at: '2022-10-11T00:46:48.72Z'
                application: APgPDQrLD52TYvqazjHJJchM
                identity: null
                merchant: MUgWbPVvtKbzjKNNGKqdQYV7
                merchant_identity: ID2CGJmjqyYaQAu6qyuvGeWK
                messages: []
                payment_instrument: PIwWisLuZNwPBoLbCgQVTCoY
                payment_instrument_verification_details:
                  push_to_card_domestic: NOT_SUPPORTED
                  push_to_card_cross_border: NOT_SUPPORTED
                  card_type: CREDIT
                  billing_currency: USD
                  issuer_country: USA
                processor: DUMMY_V1
                raw: RawDummyMerchantUnderwriteResult
                state: SUCCEEDED
                tags:
                  card_name: Personal Card
                trace_id: a7355d05-95b0-4b44-938d-bf0a99f19c17
                _links:
                  self:
                    href: https://finix.sandbox-payments-api.com/verifications/VIvZKP8XKzxyJaxJsfAEHbw6
                  application:
                    href: https://finix.sandbox-payments-api.com/applications/APgPDQrLD52TYvqazjHJJchM
                  merchant:
                    href: https://finix.sandbox-payments-api.com/merchants/MUgWbPVvtKbzjKNNGKqdQYV7
            Payment Instrument - Verify a Card’s Address:
              value:
                id: VI46ua15as1tnsWgZCFmdF9F
                created_at: '2023-02-25T20:00:33.94Z'
                updated_at: '2023-02-25T20:01:22.34Z'
                application: APgPDQrLD52TYvqazjHJJchM
                identity: null
                merchant: MUgWbPVvtKbzjKNNGKqdQYV7
                merchant_identity: ID2CGJmjqyYaQAu6qyuvGeWK
                messages: []
                payment_instrument: PIwWisLuZNwPBoLbCgQVTCoY
                payment_instrument_verification_details:
                  push_to_card_domestic: NOT_SUPPORTED
                  push_to_card_cross_border: NOT_SUPPORTED
                  card_type: CREDIT
                  billing_currency: USD
                  issuer_country: USA
                processor: DUMMY_V1
                raw: RawDummyMerchantUnderwriteResult
                state: SUCCEEDED
                tags:
                  card_name: Personal Card
                trace_id: 3374bc71-d43b-4af4-b1f8-7719a2a9e320
                _links:
                  self:
                    href: https://finix.sandbox-payments-api.com/verifications/VI46ua15as1tnsWgZCFmdF9F
                  application:
                    href: https://finix.sandbox-payments-api.com/applications/APgPDQrLD52TYvqazjHJJchM
                  merchant:
                    href: https://finix.sandbox-payments-api.com/merchants/MUgWbPVvtKbzjKNNGKqdQYV7
            Payment Instrument - Verify Push-to-Card Eligibility:
              value:
                id: VI8fgzLc9BnY1A996vPcWnu1
                created_at: '2023-01-01T10:51:06.18Z'
                updated_at: '2023-01-01T10:52:15.97Z'
                application: APgPDQrLD52TYvqazjHJJchM
                identity: null
                merchant: MUgWbPVvtKbzjKNNGKqdQYV7
                merchant_identity: ID2CGJmjqyYaQAu6qyuvGeWK
                messages: []
                payment_instrument: PIwWisLuZNwPBoLbCgQVTCoY
                payment_instrument_verification_details:
                  push_to_card_domestic: FAST_FUNDS
                  push_to_card_cross_border: NOT_SUPPORTED
                  card_type: CREDIT
                  billing_currency: USD
                  issuer_country: USA
                processor: DUMMY_V1
                raw: RawDummyMerchantUnderwriteResult
                state: SUCCEEDED
                tags:
                  card_name: Personal Card
                trace_id: 05886388-bcb3-479f-ac31-e5404a92e1ab
                _links:
                  self:
                    href: https://finix.sandbox-payments-api.com/verifications/VI8fgzLc9BnY1A996vPcWnu1
                  application:
                    href: https://finix.sandbox-payments-api.com/applications/APgPDQrLD52TYvqazjHJJchM
                  merchant:
                    href: https://finix.sandbox-payments-api.com/merchants/MUgWbPVvtKbzjKNNGKqdQYV7
      headers:
        finix-apiuser-role:
          $ref: '#/components/headers/finix-apiuser-role'
        date:
          $ref: '#/components/headers/date'
        x-request-id:
          $ref: '#/components/headers/x-request-id'
    ErrorForbidden403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error403ForbiddenList'
    ErrorUnauthorized:
      description: Authentication information is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error401Unauthorized'
  schemas:
    Address:
      title: Address
      type: object
      description: Address of the account owner.
      nullable: true
      properties:
        city:
          type: string
          description: City (max 20 characters).
          nullable: true
        country:
          $ref: '#/components/schemas/Country'
        line1:
          type: string
          description: First line of the address (max 35 characters).
          nullable: true
        line2:
          type: string
          description: Second line of the address (max 35 characters).
          nullable: true
        postal_code:
          type: string
          description: Zip or Postal code (max 7 characters).
          nullable: true
        region:
          type: string
          description: 2-letter State code.
          nullable: true
    Error406NotAcceptable:
      type: object
      properties:
        total:
          type: integer
        _embedded:
          type: object
          properties:
            errors:
              type: array
              items:
                type: object
                additionalProperties: true
                properties:
                  code:
                    type: string
                    enum:
                    - NOT_FOUND
                  logref:
                    $ref: '#/components/schemas/LogRef'
                  message:
                    type: string
                  _links:
                    type: object
                    properties:
                      source:
                        type: object
                        properties:
                          href:
                            type: string
      title: ''
    Country:
      title: Country
      type: string
      enum:
      - ABW
      - AFG
      - AGO
      - AIA
      - ALA
      - ALB
      - AND
      - ARE
      - ARG
      - ARM
      - ASM
      - ATA
      - ATF
      - ATG
      - AUS
      - AUT
      - AZE
      - BDI
      - BEL
      - BEN
      - BES
      - BFA
      - BGD
      - BGR
      - BHR
      - BHS
      - BIH
      - BLM
      - BLR
      - BLZ
      - BMU
      - BOL
      - BRA
      - BRB
      - BRN
      - BTN
      - BVT
      - BWA
      - CAF
      - CAN
      - CCK
      - CHE
      - CHL
      - CHN
      - CIV
      - CMR
      - COD
      - COG
      - COK
      - COL
      - COM
      - CPV
      - CRI
      - CUB
      - CUW
      - CXR
      - CYM
      - CYP
      - CZE
      - DEU
      - DJI
      - DMA
      - DNK
      - DOM
      - DZA
      - ECU
      - EGY
      - ERI
      - ESH
      - ESP
      - EST
      - ETH
      - FIN
      - FJI
      - FLK
      - FRA
      - FRO
      - FSM
      - GAB
      - GBR
      - GEO
      - GGY
      - GHA
      - GIB
      - GIN
      - GLP
      - GMB
      - GNB
      - GNQ
      - GRC
      - GRD
      - GRL
      - GTM
      - GUF
      - GUM
      - GUY
      - HKG
      - HMD
      - HND
      - HRV
      - HTI
      - HUN
      - IDN
      - IMN
      - IND
      - IOT
      - IRL
      - IRN
      - IRQ
      - ISL
      - ISR
      - ITA
      - JAM
      - JEY
      - JOR
      - JPN
      - KAZ
      - KEN
      - KGZ
      - KHM
      - KIR
      - KNA
      - KOR
      - KWT
      - LAO
      - LBN
      - LBR
      - LBY
      - LCA
      - LIE
      - LKA
      - LSO
      - LTU
      - LUX
      - LVA
      - MAC
      - MAF
      - MAR
      - MCO
      - MDA
      - MDG
      - MDV
      - MEX
      - MHL
      - MKD
      - MLI
      - MLT
      - MMR
      - MNE
      - MNG
      - MNP
      - MRT
      - MSR
      - MTQ
      - MUS
      - MWI
      - MYS
      - MYT
      - NAM
      - NCL
      - NER
      - NFK
      - NGA
      - NIC
      - NIU
      - NLD
      - NOR
      - NPL
      - NRU
      - NZL
      - OMN
      - PAK
      - PAN
      - PCN
      - PER
      - PHL
      - PLW
      - PNG
      - POL
      - PRI
      - PRK
      - PRT
      - PRY
      - PSE
      - PYF
      - QAT
      - REU
      - ROU
      - RUS
      - RWA
      - SAU
      - SDN
      - SEN
      - SGP
      - SGS
      - SHN
      - SJM
      - SLB
      - SLE
      - SLV
      - SMR
      - SOM
      - SPM
      - SRB
      - SSD
      - STP
      - SUR
      - SVK
      - SVN
      - SWE
      - SWZ
      - SXM
      - SYC
      - SYR
      - TCA
      - TCD
      - TGO
      - THA
      - TJK
      - TKL
      - TKM
      - TLS
      - TON
      - TTO
      - TUN
      - TUR
      - TUV
      - TWN
      - TZA
      - UGA
      - UKR
      - UMI
      - URY
      - USA
      - UZB
      - VAT
      - VCT
      - VEN
      - VGB
      - VIR
      - VNM
      - VUT
      - WLF
      - WSM
      - XKX
      - YEM
      - ZAF
      - ZMB
      - ZWE
      description: The sender’s country.
      nullable: true
    Raw:
      title: Raw
      description: Raw response from the processor.
      x-examples: {}
      type: object
      nullable: true
    Currency:
      type: string
      description: ISO 4217 3 letter currency code.
      enum:
      - AED
      - AFN
      - ALL
      - AMD
      - ANG
      - AOA
      - ARS
      - AUD
      - AWG
      - AZN
      - BAM
      - BBD
      - BDT
      - BGN
      - BHD
      - BIF
      - BMD
      - BND
      - BOB
      - BOV
      - BRL
      - BSD
      - BTN
      - BWP
      - BYR
      - BZD
      - CAD
      - CDF
      - CHE
      - CHF
      - CHW
      - CLF
      - CLP
      - CNY
      - COP
      - COU
      - CRC
      - CUC
      - CUP
      - CVE
      - CZK
      - DJF
      - DKK
      - DOP
      - DZD
      - EGP
      - ERN
      - ETB
      - EUR
      - FJD
      - FKP
      - GBP
      - GEL
      - GHS
      - GIP
      - GMD
      - GNF
      - GTQ
      - GYD
      - HKD
      - HNL
      - HRK
      - HTG
      - HUF
      - IDR
      - ILS
      - INR
      - IQD
      - IRR
      - ISK
      - JMD
      - JOD
      - JPY
      - KES
      - KGS
      - KHR
      - KMF
      - KPW
      - KRW
      - KWD
      - KYD
      - KZT
      - LAK
      - LBP
      - LKR
      - LRD
      - LSL
      - LTL
      - LYD
      - MAD
      - MDL
      - MGA
      - MKD
      - MMK
      - MNT
      - MOP
      - MRO
      - MUR
      - MVR
      - MWK
      - MXN
      - MXV
      - MYR
      - MZN
      - NAD
      - NGN
      - NIO
      - NOK
      - NPR
      - NZD
      - OMR
      - PAB
      - PEN
      - PGK
      - PHP
      - PKR
      - PLN
      - PYG
      - QAR
      - RON
      - RSD
      - RUB
      - RWF
      - SAR
      - SBD
      - SCR
      - SDG
      - SEK
      - SGD
      - SHP
      - SLL
      - SOS
      - SRD
      - SSP
      - STD
      - SVC
      - SYP
      - SZL
      - THB
      - TJS
      - TMT
      - TND
      - TOP
      - TRY
      - TTD
      - TWD
      - TZS
      - UAH
      - UGX
      - USD
      - USN
      - UYI
      - UYU
      - UZS
      - VEF
      - VND
      - VUV
      - WST
      - XAF
      - XAG
      - XAU
      - XBA
      - XBB
      - XBC
      - XBD
      - XCD
      - XDR
      - XOF
      - XPD
      - XPF
      - XPT
      - XSU
      - XTS
      - XUA
      - XXX
      - YER
      - ZAR
      - ZMW
      - ZWL
    Error401Unauthorized:
      type: object
      properties:
        total:
          type: integer
        _embedded:
          type: object
          properties:
            errors:
              type: array
              items:
                type: object
                additionalProperties: true
                properties:
                  code:
                    type: string
                    enum:
                    - UNKNOWN
                  logref:
                    $ref: '#/components/schemas/LogRef'
                  message:
                    type: string
                  _links:
                    type: object
                    additionalProperties: true
                    properties:
                      self:
                        type: object
                        properties:
                          href:
                            type: string
                      source:
                        type: object
                        properties:
                          href:
                            type: string
    ErrorGeneric:
      type: object
      properties:
        total:
          type: integer
        _embedded:
          type: object
          properties:
            errors:
              type: array
              items:
                type: object
                additionalProperties: true
                properties:
                  code:
                    type: string
                    enum:
                    - FORBIDDEN
                  logref:
                    $ref: '#/components/schemas/LogRef'
                  message:
                    type: string
                  _links:
                    type: object
                    properties:
                      source:
                        type: object
                        properties:
                          href:
                            type: string
    Verification:
      type: object
      properties:
        id:
          type: string
          description: The ID of the `Verification` attempt (begins with `VIXXX`).
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'
        application:
          type: string
          description: ID of the `Application` the `Merchant` was created under.
        identity:
          type: string
          description: ID of the `Identity` that created the `Merchant`.
          nullable: true
        merchant:
          type: string
          description: ID of the `Merchant` resource.
          nullable: true
        merchant_identity:
          type: string
          description: ID of the `Identity` associated with the `Merchant`.
          nullable: true
        messages:
          type: array
          description: Provides additional details about the verification (e.g why it failed). This field is usually **null**.
          items:
            type: object
        payment_instrument:
          type: string
          description: The `Payment Instrument` that's used to settle the `Merchant's` processed funds.
          nullable: true
        payment_instrument_verification_details:
          type: object
          description: Details the verification results of `Payment Instruments`.
          properties:
            push_to_card_domestic:
              type: string
              description: Details if the `Payment Instrument` supports push and pull from card, domestically. For more details, see [Push to Card](/guides/push-pull/).
              enum:
              - FAST_FUNDS
              - NON_FAST_FUNDS
              - NOT_SUPPORTED
              - UNKNOWN
            push_to_card_cross_border:
              type: string
              description: Details if the `Payment Instrument` supports push and pull from card, cross-border. For more details, see [Push to Card](/guides/push-pull/).
              enum:
              - FAST_FUNDS
              - NON_FAST_FUNDS
              - NOT_SUPPORTED
              - UNKNOWN
            card_type:
              type: string
              description: The type of card. Same value as `Payment Instrument#type`.
              enum:
              - CREDIT
              - DEBIT
              - HSA_FSA
              - NON_RELOADABLE_PREPAID
              - RELOADABLE_PREPAID
              - UNKNOWN
            billing_currency:
              $ref: '#/components/schemas/Currency'
            issuer_country:
              $ref: '#/components/schemas/Country'
        processor:
          type: string
          description: Name of the verification processor.
        raw:
          $ref: '#/components/schemas/Raw'
        state:
          type: string
          description: The status of the `Verification` request.
          enum:
          - PENDING
          - SUCCEEDED
          - FAILED
        tags:
          $ref: '#/components/schemas/Tags'
        trace_id:
          type: string
          description: Trace ID of the `Verification`. The processor sends back the `trace_id` so you can track the verification end-to-end.
        _links:
          type: object
          description: For your convenience, every response includes several URLs which link to resources relevant to the request. You can use these `_links` to make your follow-up requests and quickly access relevant IDs.
          properties:
            self:
              type: object
              description: Link to the resource that was used in the request.
              properties:
                href:
                  type: string
            merchant:
              type: object
              description: Link to the `Merchant` that was used in the request.
              properties:
                href:
                  type: string
            application:
              type: object
              description: Link to the `Application` that was used in the request.
              properties:
                href:
                  type: string
    Tags:
      type: object
      title: tags
      additionalProperties:
        type: string
      description: 'Include up to 50 `key`: **value** pairs to annotate requests with custom metadata.

        - Maximum character length for individual `keys` is 40.

        - Maximum character length for individual **values** is 500.


        (e.g., `order number`: **25**, `item_type`: **produce**, `department`: **sales**, etc.)'
      nullable: true
    PageCursor:
      title: PageCursor
      x-stoplight:
        id: 8v9on8n2939z2
      type: object
      properties:
        limit:
          type: integer
          description: The number of entries to return.
        next_cursor:
          type: string
          description: The cursor to use for the next page of results.
          nullable: true
      description: Details the page that's returned.
    VerificationsList:
      type: object
      x-examples:
        example-1:
          _embedded:
            verifications:
            - id: VIukL5raxiXaa4LqhUwvGxA3
              application: APgPDQrLD52TYvqazjHJJchM
              tags: {}
              messages: []
              raw: RawDummyMerchantUnderwriteResult
              processor: DUMMY_V1
              state: SUCCEEDED
              created_at: '2022-03-23T04:46:22.10Z'
              updated_at: '2022-03-23T04:47:01.79Z'
              trace_id: 2b727689-d48e-4b8a-9b86-5fc88ee519b0
              payment_instrument: null
              merchant: MUucec6fHeaWo3VHYoSkUySM
              identity: null
              merchant_identity: null
              _links:
                self:
                  href: https://finix.sandbox-payments-api.com/verifications/VIukL5raxiXaa4LqhUwvGxA3
                application:
                  href: https://finix.sandbox-payments-api.com/applications/APgPDQrLD52TYvqazjHJJchM
                merchant:
                  href: https://finix.sandbox-payments-api.com/merchants/MUucec6fHeaWo3VHYoSkUySM
            - id: VIdikDHXv7x8nWyJg8JZemGx
              application: APgPDQrLD52TYvqazjHJJchM
              tags:
                key_2: value_2
              messages: []
              raw: RawDummyMerchantUnderwriteResult
              processor: DUMMY_V1
              state: SUCCEEDED
              created_at: '2022-01-27T07:36:58.21Z'
              updated_at: '2022-01-27T07:36:58.46Z'
              trace_id: 86e00b16-8b94-44fb-bb0f-d5c32c887133
              payment_instrument: null
              merchant: MUucec6fHeaWo3VHYoSkUySM
              identity: null
              merchant_identity: null
              _links:
                self:
                  href: https://finix.sandbox-payments-api.com/verifications/VIdikDHXv7x8nWyJg8JZemGx
                application:
                  href: https://finix.sandbox-payments-api.com/applications/APgPDQrLD52TYvqazjHJJchM
                merchant:
                  href: https://finix.sandbox-payments-api.com/merchants/MUucec6fHeaWo3VHYoSkUySM
          _links:
            self:
              href: https://finix.sandbox-payments-api.com/merchants/MUucec6fHeaWo3VHYoSkUySM/verifications?offset=0&limit=20&sort=created_at,desc&sort=id,desc
          page:
            limit: 20
            next_cursor: VIdikDHXv7x8nWyJg8JZemGx
      properties:
        _embedded:
          type: object
          description: List of `Verifications`.
          properties:
            verifications:
              type: array
              minItems: 0
              uniqueItems: true
              description: '`Verification` resources.'
              items:
                $ref: '#/components/schemas/Verification'
        _links:
          $ref: '#/components/schemas/ListLinks'
        page:
          $ref: '#/components/schemas/PageCursor'
    Error403ForbiddenList:
      type: object
      properties:
        total:
          type: integer
        _embedded:
          type: object
          properties:
            errors:
              type: array
              items:
                type: object
                additionalProperties: true
                properties:
                  code:
                    type: string
                    enum:
                    - FORBIDDEN
                  logref:
                    $ref: '#/components/schemas/LogRef'
                  message:
                    type: string
                  _links:
                    type: object
                    properties:
                      source:
                        type: object
                        properties:
                          href:
                            type: string
      description: ''
      title: ''
    ListLinks:
      title: ListLinks
      additionalProperties: true
      type: object
      description: For your convenience, every response includes several URLs which link to resources relevant to the request. You can use these `_links` to make your follow-up requests and quickly access relevant IDs.
      properties:
        next:
          type: object
          description: Link to the next page of entries.
          properties:
            href:
              type: string
        self:
          type: object
          description: Link to the resource that was used in the request.
          properties:
            href:
              type: string
    CreateVerificationRequest:
      type: object
      properties:
        merchant:
          type: string
          description: '- The ID of the `Merchant`.

            - Must be included when `verify_payment_card` is set to **true**.'
        processor:
          type: string
          enum:
          - DUMMY_V1
          - MASTERCARD_V1
          - VISA_V1
          default: DUMMY_V1
          description: 'Set the acquiring processor. Avalible values include: <ul><li><strong>DUMMY_V1</strong></li><li><strong>MASTERCARD_V1</strong></li><li><strong>VISA_V1</strong></li></ul>Use <strong>DUMMY_V1</strong> or  <strong>null</strong> to use your sandbox. For more details on which processor to use, reach out to your Finix point of contact or email <a href="/guides/getting-started/support-at-finix/">Finix Support</a>.'
        security_code:
          type: string
          description: The ID of the `Merchant`.
        verify_payment_card:
          type: boolean
          description: '- Set to **true** to verify card details with the card issuer.

            - Must be set to **true** to update the CVV or security code of a card.

            - When set to **true**, `merchant` must also be included with your request.'
        tags:
          $ref: '#/components/schemas/Tags'
        address:
          $ref: '#/components/schemas/Address'
        identity:
          type: string
          description: ID of the `Identity` resource associated with the `Merchant`.
    Error404NotFoundList:
      type: object
      properties:
        total:
          type: integer
        _embedded:
          type: object
          properties:
            errors:
              type: array
              items:
                type: object
                additionalProperties: true
                properties:
                  code:
                    type: string
                    enum:
                    - NOT_FOUND
                  logref:
                    $ref: '#/components/schemas/LogRef'
                  message:
                    type: string
                  _links:
                    type: object
                    properties:
                      source:
                        type: object
                        properties:
                          href:
                            type: string
    UpdatedAt:
      type: string
      title: UpdatedAt
      format: date-time
      description: Timestamp of when the object was last updated.
    Error422InvalidFieldList:
      type: object
      description: Invalid field
      title: ''
      properties:
        total:
          type: integer
        _embedded:
          type: object
          properties:
            errors:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    enum:
                    - INVALID_FIELD
                  field:
                    type: string
                  logref:
                    $ref: '#/components/schemas/LogRef'
                  message:
                    type: string
                  _links:
                    type: object
                    properties:
                      source:
                        type: object
                        properties:
                          href:
                            type: string
    LogRef:
      title: LogRef
      type: object
      properties:
        logref:
          type: string
    CreatedAt:
      type: string
      title: CreatedAt
      format: date-time
      description: Timestamp of when the object was created.
  headers:
    finix-apiuser-role:
      schema:
        type: string
        enum:
        - ROLE_ADMIN
        - ROLE_PLATFORM
        - ROLE_PARTNER
        - ROLE_MERCHANT
    x-request-id:
      description: A unique ID for this specific API request attempt.
      schema:
        type: string
    date:
      schema:
        type: string
  requestBodies:
    CreateVerificationRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateVerificationRequest'
          examples:
            Payment Instrument - Verify a Card’s CVV:
              value:
                merchant: MUgWbPVvtKbzjKNNGKqdQYV7
                security_code: '123'
                verify_payment_card: true
            Payment Instrument - Verify a Card’s Address:
              value:
                address:
                  city: San Francisco
                  country: USA
                  line1: 900 Metro Center Blv
                  postal_code: '94404'
                  region: CA
                merchant: MUgWbPVvtKbzjKNNGKqdQYV7
                verify_payment_card: true
            Payment Instrument - Verify Push-to-Card Eligibility:
              value:
                identity: ID2CGJmjqyYaQAu6qyuvGeWK
                merchant: MUgWbPVvtKbzjKNNGKqdQYV7
                tags:
                  card_name: Business_Card
  parameters:
    QueryBeforeCursor:
      name: before_cursor
      in: query
      required: false
      schema:
        type: string
      description: Return every resource created before the cursor value.
    QueryAfterCursor:
      name: after_cursor
      in: query
      required: false
      schema:
        type: string
      description: Return every resource created after the cursor value.
    QueryLimit:
      description: The numbers of items to return.
      example: 10
      in: query
      name: limit
      schema:
        type: integer
      style: form
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      description: ''
x-stoplight:
  id: c6861590dda46
x-ignoredHeaderParameters:
- Accept
- finix-apiuser-role
- date
- x-request-id
x-tagGroups:
- name: MAIN RESOURCES
  tags:
  - Authorizations
  - Compliance Forms
  - Devices
  - Disputes
  - Fee Profiles
  - Files
  - Identities
  - Instrument Updates
  - Merchants
  - Onboarding Forms
  - Payment Instruments
  - Settlements
  - Split Transfers
  - Transfers
  - Users
  - Webhooks
- name: CORE-PAYFAC RESOURCES
  tags:
  - Application Profiles
  - Applications
  - Balance Transfers
  - Merchant Profiles
  - Payout Profiles
  - Verifications
- name: SUBSCRIPTION BILLING
  tags:
  - Subscription Schedules
  - Subscription Amounts
  - Subscription Enrollments
x-exclude-tags-from-libraries:
- Applications
- Application Profiles
- Fees
- Payment Instruments P2C
- Processors
- Review Queue
- Subscription Schedules
- Subscription Amounts
- Subscription Enrollments
- Users
